### ISSUE TITLE
bandcli keys migrate to guanyu mainnet fails

### ISSUE THREAD

**Issue by joesixpack** [bandprotocol/bandchain#2759]
```
j@milkyway:~$ bandcli keys migrate
Migrating key: 'joesixpack (local)' ...
Skip key migration? [y/N]: n
Enter passphrase to decrypt key:
panic: No such interface “org.freedesktop.DBus.Properties” on object at path /

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeInfo(0x13f2860, 0x13f2858, 0xc000c1e740, 0x1, 0x1, 0xc000c1e750, 0x1, 0x1, 0x158e180, 0xc000195c50, ...)
        /home/j/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:478 +0x38c
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeLocalKey(0x13f2860, 0x13f2858, 0xc000c1e740, 0x1, 0x1, 0xc000c1e750, 0x1, 0x1, 0x158e180, 0xc000195c50, ...)
        /home/j/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:464 +0x189
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.ImportPrivKey(0x13f2860, 0x13f2858, 0xc000c1e740, 0x1, 0x1, 0xc000c1e750, 0x1, 0x1, 0x158e180, 0xc000195c50, ...)
        /home/j/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/crypto/keys/keyring.go:356 +0x182
github.com/cosmos/cosmos-sdk/client/keys.runMigrateCmd(0xc000fad8c0, 0x1e785c8, 0x0, 0x0, 0x0, 0x0)
        /home/j/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.1/client/keys/migrate.go:131 +0x887
github.com/spf13/cobra.(*Command).execute(0xc000fad8c0, 0x1e785c8, 0x0, 0x0, 0xc000fad8c0, 0x1e785c8)
        /home/j/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00001ab00, 0x89c530, 0xc00001ab00, 0x11ed19d)
        /home/j/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/j/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00001ab00, 0x13f5388, 0x4, 0xc000ef3bf0)
        /home/j/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/libs/cli/setup.go:89 +0x3c
main.main()
        /home/j/bandchain/chain/cmd/bandcli/main.go:72 +0x351
```

**Comment by taobun** [comment]
What's os on your validator node? It seems to be a problem from keyring os. https://github.com/99designs/aws-vault/issues/304

**Comment by joesixpack** [comment]
Ubuntu 20.04 LTS.  I tried that fix at the link referenced, but did not help.
