### ISSUE TITLE
rpc-server breaks if serving heavy request which needs >30s in total

### ISSUE THREAD

**Issue by jun0tpyrc** [bandprotocol/bandchain#3093]
```
E[2021-01-20|12:19:12.218] Panic in RPC HTTP handler                    module=rpc-server err="write tcp 127.0.0.1:26657->127.0.0.1:49766: i/o timeout" stack="goroutine 139715 [running]:\nruntime/debug.Stack(0x132c140, 0x136f8c0, 0xc0aeab8190)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1.2(0xc08a5ee2c0, 0x18b8bc0, 0xc00fb743e0, 0xbffa25c7d7c1ebbf, 0x32e4901b17, 0x250b040, 0xc0886adc00)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:191 +0x16d\npanic(0x136f8c0, 0xc0aeab8190)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.WriteRPCResponseHTTP(0x18b1f80, 0xc08a5ee2c0, 0x14be52e, 0x3, 0x1894fe0, 0xc08a5b9220, 0xc0bde40000, 0x10a9a, 0x1fd2e, 0x0)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:117 +0x281\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.WriteRPCResponseArrayHTTP(0x18b1f80, 0xc08a5ee2c0, 0xc0ae3a5d40, 0x1, 0x1)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:126 +0xca\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1(0x18b1f80, 0xc08a5ee2c0, 0xc0886adc00)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_json_handler.go:113 +0x479\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1(0x18b1f80, 0xc08a5ee2c0, 0xc0886adc00)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_json_handler.go:127 +0x9c\nnet/http.HandlerFunc.ServeHTTP(0xc01091c300, 0x18b1f80, 0xc08a5ee2c0, 0xc0886adc00)\n\t/usr/local/go/src/net/http/server.go:2041 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc0109141c0, 0x18b1f80, 0xc08a5ee2c0, 0xc0886adc00)\n\t/usr/local/go/src/net/http/server.go:2416 +0x1a5\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP(0x1893640, 0xc0109141c0, 0xf4240, 0x18b1f80, 0xc08a5ee2c0, 0xc0886adc00)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:240 +0xcf\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1(0x18b2780, 0xc15efdfce0, 0xc0886adc00)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:213 +0x38e\nnet/http.HandlerFunc.ServeHTTP(0xc05664c450, 0x18b2780, 0xc15efdfce0, 0xc0886adc00)\n\t/usr/local/go/src/net/http/server.go:2041 +0x44\nnet/http.serverHandler.ServeHTTP(0xc05667a0e0, 0x18b2780, 0xc15efdfce0, 0xc0886adc00)\n\t/usr/local/go/src/net/http/server.go:2836 +0xa3\nnet/http.(*conn).serve(0xc1802ab040, 0x18b8140, 0xc1802fabc0)\n\t/usr/local/go/src/net/http/server.go:1924 +0x86c\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2962 +0x35c\n"
2021/01/20 12:19:12 http: superfluous response.WriteHeader call from github.com/tendermint/tendermint/rpc/jsonrpc/server.(*responseWriterWrapper).WriteHeader (http_server.go:225)
Panic during RPC panic recovery: write tcp 127.0.0.1:26657->127.0.0.1:49766: i/o timeout
goroutine 139715 [running]:
runtime/debug.Stack(0xc00288edc8, 0x136f8c0, 0xc0aeab8190)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1.1(0x18b2780, 0xc15efdfce0)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:162 +0x6e
panic(0x136f8c0, 0xc0aeab8190)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/tendermint/tendermint/rpc/jsonrpc/server.WriteRPCResponseHTTPError(0x18b1f80, 0xc08a5ee2c0, 0x1f4, 0x14be52e, 0x3, 0x1894fe0, 0x18677d8, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:105 +0x285
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1.2(0xc08a5ee2c0, 0x18b8bc0, 0xc00fb743e0, 0xbffa25c7d7c1ebbf, 0x32e4901b17, 0x250b040, 0xc0886adc00)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:193 +0x33e
panic(0x136f8c0, 0xc0aeab8190)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/tendermint/tendermint/rpc/jsonrpc/server.WriteRPCResponseHTTP(0x18b1f80, 0xc08a5ee2c0, 0x14be52e, 0x3, 0x1894fe0, 0xc08a5b9220, 0xc0bde40000, 0x10a9a, 0x1fd2e, 0x0)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:117 +0x281
github.com/tendermint/tendermint/rpc/jsonrpc/server.WriteRPCResponseArrayHTTP(0x18b1f80, 0xc08a5ee2c0, 0xc0ae3a5d40, 0x1, 0x1)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:126 +0xca
github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1(0x18b1f80, 0xc08a5ee2c0, 0xc0886adc00)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_json_handler.go:113 +0x479
github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1(0x18b1f80, 0xc08a5ee2c0, 0xc0886adc00)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_json_handler.go:127 +0x9c
net/http.HandlerFunc.ServeHTTP(0xc01091c300, 0x18b1f80, 0xc08a5ee2c0, 0xc0886adc00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0109141c0, 0x18b1f80, 0xc08a5ee2c0, 0xc0886adc00)
	/usr/local/go/src/net/http/server.go:2416 +0x1a5
github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP(0x1893640, 0xc0109141c0, 0xf4240, 0x18b1f80, 0xc08a5ee2c0, 0xc0886adc00)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:240 +0xcf
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1(0x18b2780, 0xc15efdfce0, 0xc0886adc00)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/rpc/jsonrpc/server/http_server.go:213 +0x38e
net/http.HandlerFunc.ServeHTTP(0xc05664c450, 0x18b2780, 0xc15efdfce0, 0xc0886adc00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
net/http.serverHandler.ServeHTTP(0xc05667a0e0, 0x18b2780, 0xc15efdfce0, 0xc0886adc00)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc1802ab040, 0x18b8140, 0xc1802fabc0)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c

2021/01/20 12:19:12 http: superfluous response.WriteHeader call from github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1.1 (http_server.go:163)
```

seems no related config to surpass this

**Comment by jun0tpyrc** [comment]
the config `timeout_broadcast_tx_commit` looks apply,  not only for `broadcast tx`
